### ISSUE TITLE
"MockInstance: side effects have been detected" hard to track

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#1046]
Hi there ! Hope you're doing well and that you took some time for yourself during the summer !

I've seen recently that `ng-mocks` triggers warnings about `MockInstance` incorrectly cleaned up. Thing is, I have plenty of tests, and plenty of files, so its kinda hard to find **where** the issue occurs. Would it be possible to add a context or something ? Or add an option so that affected test fails completely ?

:beers: cheers !

**Comment by satanTime** [comment]
Hi @GerkinDev,

Yep, I'm still think about how to find the best way to mock them before initialization and that jest issue, which is ignored by maintainers, spoils everything.

Usually, what I do is that I enable additional logging myself, then, at least, it helps to understand affected tests: https://github.com/ike18t/ng-mocks/blob/master/karma-test-shim.ts#L39-L46

Not sure if it's working for jest without the jasmine runner.
Please let me know if it has helped, otherwise I can add a config flag which would fail instead of a warning.

**Comment by satanTime** [comment]
Also, a question. Did you configure this setup: https://ng-mocks.sudo.eu/extra/install#default-customizations? Or you use jest 27+?

**Comment by satanTime** [comment]
I think I found the issue. Please check the next release once it has been published.

**Comment by GerkinDev** [comment]
Hi there ! Sorry, I was quite busy laying some code to write EBNF syntax on the fly lol

I didn't had the time to try those options. I'll try it next time I leave my feature branch

Cheers !

**Comment by satanTime** [comment]
[v12.5.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
