### ISSUE TITLE
Allow to get control value from MockControlValueAccessor

### ISSUE THREAD

**Issue by everkin** [ike18t/ng-mocks#126]
When testing angular components, we use the Page Object pattern to simulate the user experience and access the form field not through the component, but through view. Thus, we check the correctness of the bindings in the template and abstract from the internal implementation. In this case, we can change the Reactive Forms to Template-Driven Forms without changing the tests. So, I would like to refer to the control value not directly, but indirectly, through the template.

Example

   ```
 ngOnInit() {
        this.loginService.getLogin().subscribe(login => this.loginControl.setValue(login));
    }
```

```
it('If login comes in, then it is put in the form field', () => {
    // arrange
    when(loginServiceMock.getLogin()).thenReturn('login');

    // act
    fixture.detectChanges();

    // assert
    expect(pageObject.loginInput.__value).toBe('login');
});
```

**Comment by satanTime** [comment]
I think in this test you need to assert that `this.loginControl.setValue` has been called with `login` because there's no dependency on the login input inside of `ngOnInit`

**Comment by vladiag** [comment]
@satanTime In your version you will work with controller of component, in our case we are trying to abstract of realisation and write test on component as Black Box. We have template and mocking of data and out tests writing as Controller not exists, in my opinion it's better, than i will assert that i have formControl, than i will test that i call method on FormControl, after 2 weeks i decide to use NgModel and i will rewrite all my tests, just because i test realisation

**Comment by satanTime** [comment]
That's exactly the reason to test right things. Because if after 2 weeks you decide to use in the test a real component instead of the mocked one the test will fail due to missed `__value` in the real comment, when normally it shouldn't happen.

**Comment by everkin** [comment]
But this is unit tests, they should mocking not only services, but also components.
If you consciously change the environment of a unit test, then the tests themselves can change
__simulateChange is not present in real components either

**Comment by vladiag** [comment]
Alse can add, that ControlValueAccessor - it input and outputs what you are writing in your post, we don't want about realisation (NgModel, FormControl, FormControlDirective, etc.), we only know about ControlValueAccessor with their contract

**Comment by vladiag** [comment]
Additionaly, we can overthink current vision and Inject NgControl in current mocked component and make it public, i think that will more more flexible, because
1. we can delete __simulateChange, __simulateTouched,
2. can test validity, touched, dirty and other property of control
3. still don't know about realisation

**Comment by satanTime** [comment]
if you test the component as black box then it means that `loginControl` and `loginService` are parts of its public interface, we pretend we don't know how it's used inside.
From our business requirements we know if we call `loginService.getLogin()` it should affect `loginControl.setValue` and this part should be covered.

Another black box part is the component's template and how it used `loginControl`. Because in the template it's passed to a form-control component as `[formControl]="loginControl"` we should assert it, if the code will be changed to `[ngModel]="loginControl.value" (ngModel)="loginControl.setValue($event)"` we we should rewrite our test, because the agreement has been changed.

2: @everkin, this part of an old api, the right way is to add a spy on `registerOnChange`, `registerOnTouched` or `writeValue`, I think you can add spy instead of asserting `__value`, aren't you?

2: @vladiag, you are totally right: we don't want to know about realisation. You don't want to know about NgModel, FormControl, FormControlDirective, etc. the same as you don't want to know about `ControlValueAccessor` too. You should simply assert that an element received an input like `formControlName="test"` or `[formControl]="control"` or `[ngModel]...`, nobody cares what it does under the hood.

**Comment by satanTime** [comment]
2: @vladiag, about removal of `__simulateChange` and `__simulateTouched`, it makes sense, but I think first we need to deprecate them with a proper example.

What about a spy on `writeValue` call?

it('If login comes in, then it is put in the form field', () => {
    // arrange
    spyOn(pageObject.loginInput, 'writeValue');
    when(loginServiceMock.getLogin()).thenReturn('login');

    // act
    fixture.detectChanges();

    // assert
    expect(pageObject.loginInput.writeValue).toHaveBeenCalledWith('login');
});

**Comment by satanTime** [comment]
I think `__simulateChange` and `__simulateTouched` confuse people with how to work with mocked `ControlValueAccessor` and should be deprecated. The right way should be a usage of spies on them or something else, this part requires a proper investigation first.

Please let me know what you think.

**Comment by vladiag** [comment]
We will stop on spies, that cover out request) thx @satanTime

**Comment by satanTime** [comment]
Great, I like this way too. If you want you can update the PR with better readme on how to work with `ControlValueAccessor` and spies.

**Comment by vladiag** [comment]
But i think it's not right that when i change form `[formControl]="loginControl"` to `[ngModel]="loginControl.value" (ngModeChangel)="loginControl.setValue($event)"` i should rewrite tests (with spies i will not rewrite, it's just for record)

**Comment by satanTime** [comment]
The thing about `formControl` and `ngModel` is that they should be mocked as all other dependencies in unit tests too, therefore there won't be code that calls `writeValue` and therefore we can't rely on assertions of `writeValue`, we can only check that we passed proper inputs / outputs and believe that real directives work as expected.
