### ISSUE TITLE
ES5 target support + Angular 10 Support

### ISSUE THREAD

**Issue by icorne** [ike18t/ng-mocks#158]
Hello,

This is the only library I encountered thus far that does not support ES5 target anymore..
Could it be because in https://github.com/satanTime/ng-mocks/blob/83debd26ac89ed5ae5efb3c9be8ce7ad91ad6c64/e2e/a10es2015ivy/.browserslistrc you excluded IE11?

Can we try and revisit this?

**Comment by satanTime** [comment]
Hi,

the lib does support es5, but angular 10 doesn't support it and always uses es2015 version of an imported lib.

I spent around 2 weeks to determine a solution and failed with every idea.

Feel free to try to fix it yourself, perhaps you'll find a working solution.

**Comment by icorne** [comment]
I can have a look when I find some time. 
Where did you find that angular 10 does not support ES5 target?
We've got a pretty extensive app (hybrid with angularjs even) and everything is working except my tests which use ng-mocks.

**Comment by satanTime** [comment]
During investigation, starting from angular 10 it ignores es5 build even it has been provided: https://github.com/ike18t/ng-mocks/blob/master/package.json#L5-L8.

I think in your app dependencies don't extend code base built by es5 and es2015, in case of ng-mocks if a component was built as es2015 and ng-mocks was built as es5 then it throws an error that an instance can't be created without using `new` operator that is required in es2015. Because es2015 is more popular it is the default build target.

Perhaps there's a way to downgrade to es5 not only the app itself, but also installed dependencies.

Current solution is to change tsconfig.spec.ts to use es2015.

**Comment by satanTime** [comment]
Note: As an option to try: eval with detection of es6 classes.

**Comment by satanTime** [comment]
Hi, might you check that https://github.com/ike18t/ng-mocks/pull/161 works for you on es5?
