### ISSUE TITLE
Is there any way to mock the service, example MockService.

### ISSUE THREAD

**Issue by Taquita** [ike18t/ng-mocks#16]
Sorry, I'm a beginner with tests on the Angular and on Jasmine, I figured out a way to perform the Mock of an angular service.

class MockSalesReportService extends SalesReportService {
  public getSalesForPeriod(initial: Date, final: Date) {
    return  null;
  }

beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ SalesReportComponent ],
      imports: [ MockModule(MzDatepickerModule) ],
      providers: [ { provide: SalesReportService, useClass: MockSalesReportService} ]
    })
    .compileComponents();
  }));

I would like to know if you have something more practical in the library ?, Based on the principle that I did not find a MockService in the packages.

Sorry for my english, I used google translate :v:

**Comment by ike18t** [comment]
Hi @Taquita ! 

This was pretty easy to understand so Google Translate did a good job. Hopefully it translates this back just as well. 

Technically with MockModule providers are getting setup in the testbed with empty objects because I don't want to make assumptions on how the provider will be used and don't want to mask issues by having everything noop. What I typically do is setup a provider in a way similar to what you did but rather than using "useClass" I use "useValue" and provide a mock of the object. 

I wrote a mocking library that makes creating mocks very simple with type-safety and allows you to only mock what you care about so that it is more obvious in the tests what you are trying to accomplish. That's the mocking library I use but that pattern will work with whatever mocking library you prefer.

mocking lib:
https://www.npmjs.com/package/ts-mockery

or if you are on an older version of typescript:
https://www.npmjs.com/package/ts-mocks

Example: 
```typescript
import { Mock } from 'ts-mockery';

beforeEach(async(() => {
  TestBed.configureTestingModule({
    declarations: [ SalesReportComponent ],
    imports: [ MockModule(MzDatepickerModule) ],
    providers: [ { 
      provide: SalesReportService, 
      useValue: Mock.of<SalesReportService>({ getSalesForPeriod: Mock.noop })
    } ]
  })
  .compileComponents();
}));
```

Hopefully this makes sense after translation. 😅

**Comment by Taquita** [comment]
@ike18t Thanks

Google translator helped yes, thank you very much, I will test the libraries.

**Comment by ike18t** [comment]
Hey @Taquita ,

How'd it go? Did you get past your blocker?

**Comment by Taquita** [comment]
Hey, @ike18t ,

yes, I'm with other doubts, but referring to something else now, if you can give me a tip. :)!

but it runs away from this topic, and its library.

**Comment by ike18t** [comment]
@Taquita 

Sure, what are you running into now?

**Comment by ike18t** [comment]
Are the builders necessary? Do your tests require that much preconfigured state? Or can you get away with just stubbing out the state that you actually care about?  

If you do need the builders, the standard I typically see is to have a "spec-helpers" directory and have builders be a sub-directory of that. Then you can create a path alias in your tsconfig (https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) for spec-helpers to use for importing.

**Comment by Taquita** [comment]
@ike18t 

Thank you, it seems like a great solution,
:)

**Comment by ike18t** [comment]
If you don't mind, I'm going to go ahead and close this issue.

**Comment by Taquita** [comment]
OK! you can close.

**Comment by satanTime** [comment]
Update: [mock services](https://github.com/ike18t/ng-mocks#how-to-create-a-mock-service) and [mock providers](https://github.com/ike18t/ng-mocks#how-to-create-a-mock-provider) are supported by `ng-mocks`.
