### ISSUE TITLE
Issue with MatTable using MatSort

### ISSUE THREAD

**Issue by Dji75** [ike18t/ng-mocks#568]
I have a problem with ngMocks, MatTableModule and MatSortModule.

If I have the mat-table sort initialization in the `ngOnInit` (or `ngAfterViewInit`, like Angular Material documents), I've got the following error:
```
  TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

Component's code:
```typescript
  ...
  datasource = new MatTableDataSource<object>([]);
  @ViewChild(MatSort, { static: true }) mySort: MatSort = new MatSort();

  ngOnInit(): void {
    this.datasource.sort = this.mySort;
  }
  ...
```

If I move the sort initialization in the constructor, it works.
I can use my init in the constructor but on my point of view, it would also work if initialization is present in ngOnInit, right ?

**Comment by satanTime** [comment]
Hi @Dji75,

thanks for the report.

I would assume that in `ngOnInit` or `ngAfterViewInit`, `@ViewChild` has an affect, whereas in ctor `new MatSort();`.
Looks like `MatSort` is mocked, therefore `ViewChild` gets it.
Because all mocked things don't return streams - the test fails.

Do you know which property is `undefined`?

I would suggest to use [`MockInstance`](https://ng-mocks.sudo.eu/api/MockInstance) or [`ngMocks.defaultMock`](https://ng-mocks.sudo.eu/api/ngMocks/defaultMock) here:

```ts
it('asadfsadf', () => {
  MockInstance(MatSort, 'streamPropWeNeedToStub$', EMPTY);
  const fixture = MockRender(CompoenntWithMatSort);
});
```

or in `test.ts`, then it will be `EMPTY` for all tests by default:

```ts
ngMocks.defaultMock(MatSort, () => ({
  streamPropWeNeedToStub: EMPTY,
}));
```

**Comment by Dji75** [comment]
I got the build error
```
Error: src/test.ts:33:1 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(token: InjectionToken<{ streamPropWeNeedToStub: Observable<never>; }>, handler?: (value: { streamPropWeNeedToStub: Observable<never>; }, injector: Injector) => Partial<...>): void', gave the following error.
    Argument of type 'typeof MatSort' is not assignable to parameter of type 'InjectionToken<{ streamPropWeNeedToStub: Observable<never>; }>'.
      Type 'typeof MatSort' is missing the following properties from type 'InjectionToken<{ streamPropWeNeedToStub: Observable<never>; }>': _desc, ɵprov
  Overload 2 of 3, '(token: string, handler?: (value: { streamPropWeNeedToStub: Observable<never>; }, injector: Injector) => Partial<{ streamPropWeNeedToStub: Observable<never>; }>): void', gave the following error.
    Argument of type 'typeof MatSort' is not assignable to parameter of type 'string'.
  Overload 3 of 3, '(def: AnyType<MatSort>, handler?: (value: MatSort, injector: Injector) => void | Partial<MatSort>): void', gave the following error.
    Type '{ streamPropWeNeedToStub: Observable<never>; }' is not assignable to type 'void | Partial<MatSort>'.
      Type '{ streamPropWeNeedToStub: Observable<never>; }' has no properties in common with type 'Partial<MatSort>'.
      ```

**Comment by Dji75** [comment]
It was `initialized`, with this code it works:
```
      ngMocks.defaultMock(MatSort, () => ({
        initialized: EMPTY,
      }));
```

**Comment by Dji75** [comment]
It seems all material components which implements `HasInitialized` would have same issue with default mock.

**Comment by satanTime** [comment]
Right, this is the biggest downside of mocks in my option.
Currently it is impossible to detect which properties / functions should return observables / promises, in other words to detect return time at runtime.

Even more, it is not always possible to detect all the properties a js class has. Thanks God, that a class prototype has all methods at least.

That's why `ngMocks.defaultMock` was invented. The idea was that devs would define in a single place all observable / promise types of mock properties / methods 
they need to handle.

Maybe we can do a kind of present for well known libraries and their declarations so  `MatSort.initialized` would be `EMPTY` by default, but not sure how to collect all the data for it.

**Comment by satanTime** [comment]
I think for now I could extend `ngMocks.defaultMock` in order to accept an array of classes. So there wouldn't be a need to copypaste the same code again and again.

```ts
ngMocks.defaultMock([MatSort, MatResort, MatCurort], () => ({
  initialized: EMPTY,
}));
```

Would it help? what are you thoughts on that?

**Comment by Dji75** [comment]
It's always a good idea to mutualize code wherever it make sense, and this is the case here. Looks good for me ! :+1:

**Comment by satanTime** [comment]
Hi @Dji75,

thanks for the feedback. I'm releasing these changes, they will be published the next hour.

The next step for me is to solve the issue you mentioned in another ticket, regarding store. Would be nice if you could find time to provide an example there.

Thank you in advance and happy coding!

**Comment by satanTime** [comment]
[v12.0.1](https://github.com/ike18t/ng-mocks/releases/tag/v12.0.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
