### ISSUE TITLE
MockRender fixture.detectChanges() call

### ISSUE THREAD

**Issue by kekel87** [ike18t/ng-mocks#67]
Hey, we encounter an issue when we using MockRender.
We want to check stuff in `ngAfterViewInit` of tested child component.
But in [MockRender](https://github.com/ike18t/ng-mocks/blob/452818b52ce19d60bbe200fdddb8a14a84303f15/lib/mock-render/mock-render.ts#L60) you call `fixture.detectChanges();`, it's impossible to spy what's going on inside.

It's possible to remove this or make it parametrizable ?
Thanks.

**Comment by aymeric-duchein** [comment]
Hi! I have a similar problem. I'm trying to spy something done inside the constructor of my component.
The issue here is that spies are reset by the `TestBed.configureTestingModule` call. But to achieve what we want, we have to add our spies before the `TestBed.createComponent` call.

A solution to this problem would be to change the mockRender function signature to something like 
(the name of the parameter may be improved 😉 )

```ts
function MockRenderX<MComponent, TComponent extends {[key: string]: any}>(
  template: string | Type<MComponent>,
  params?: TComponent,
  initSpies?: () => void
)
```

and change the end of the function like this: 

```ts

  // Injection of our template.
  TestBed.configureTestingModule({
    declarations: [component],
  });

  if (initSpies) {
    initSpies();
  }

  const fixture = TestBed.createComponent(component);
  fixture.detectChanges();
  return fixture;
```

I will gladly create a PR if this idea suits you.

**Comment by ike18t** [comment]
I added an arg to MockRender to allow more control of when detect changes fires by allowing the user to tell it not to fire. This will allow the user to trigger it themselves. Let me know what you think.

**Comment by kekel87** [comment]
Hi, thank you for your responsiveness. I left you a comment on PR.

**Comment by kekel87** [comment]
I think it would be better if it was false by default.

**Comment by satanTime** [comment]
The fix has been merged and will be released tomorrow.

**Comment by satanTime** [comment]
Please check 9.3.0
