### ISSUE TITLE
add ESM and Export Map

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#702]
- https://docs.skypack.dev/package-authors/package-checks#esm
- https://docs.skypack.dev/package-authors/package-checks#export-map

**Comment by satanTime** [comment]
[v12.1.1](https://github.com/ike18t/ng-mocks/releases/tag/v12.1.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by GerkinDev** [comment]
Hi there,

I was wondering what was the state if this issue. Recent releases only declares the `type` as `commonjs` and with only a `main` in `cjs`, `esm` build isn't exported at all.

In the meantime, I've successfully moved several of my libs with both `ESM` & `CJS` support, with auto-fallbacks, so maybe I could give a hand.

On one hand, jest does not support ESM very well: it works, but it needs some time to search, so I'm afraid offering this ability would cause more issues related to ESM specificities with jest, than offering a real improvement. Moreover, since this lib is not intended to be built in the application, tree shaking compliance of ESM is not really necessary.
On the other hand, this would be future-proof, possibly helping with future perf improvements and stability of static imports, and eventually support Deno if Angular comes to a point where this is possible.
