### ISSUE TITLE
improve docs about most common errors 

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#782]

**Comment by neilsoult** [comment]
Is `Expected to be running in 'ProxyZone', but it was not found.` a common error? I am upgrading to angular 13 and upgrading ng-mocks from 12.5.0 to 13.4.0. This seems to come from importing 'zone.js/testing', which is not a requirement from angular 13 but from ng-mocks 13, so that is why I ask. I am having a difficult time finding any documentation about this error other than it's supposedly related to `FakeAsync`, which I am not using in any of my tests.

**Comment by satanTime** [comment]
Hi. That's definitely a bug. Thanks for the reporting. I'll fix it in the next release.

**Comment by satanTime** [comment]
[v13.4.1](https://github.com/ike18t/ng-mocks/releases/tag/v13.4.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
