### ISSUE TITLE
Modifying component input on the wrapper modifies the param object supplied to MockRender

### ISSUE THREAD

**Issue by jneuhaus20** [ike18t/ng-mocks#839]
### Scenario:
A Component has an Input:

```ts
class AppComponent {
  @Input()
  name: string = 'default';

  constructor() {}
}
```

A param object including a value for this input is supplied to `MockRender`:
```ts
const params = {
  name: 'originalParam'
};
fixture = MockRender(AppComponent, params);
```

The _wrapper_ input is modified:
```ts
fixture.componentInstance.name = 'modifiedOnWrapper'; // not fixture.point.componentInstance
fixture.detectChanges();
```

### Expected result:
Only the wrapper input and component inputs are modified:
```js
expect(fixture.componentInstance.name).toBe('modifiedOnWrapper');
expect(fixture.point.componentInstance.name).toBe('modifiedOnWrapper');
```

### Actual result:
The param object is also modified:
```js
expect(params.name).toBe('originalParam'); // Fails
```

[Example in Stackblitz](https://stackblitz.com/edit/github-zfdnjo-oa8uhj?devtoolsheight=33&file=src/examples/main/test.spec.ts)

### Additional Info:
ng-mocks version: 11.11.2 in my project, 12.3.1 in the StackBlitz example

I expected references to be maintained, otherwise you couldn't provide a spy via the param object and assert on it, but I didn't expect assigning a string literal to the wrapper's input property to also modify the param object.  In the docs, it's also a bit unclear which is preferred, assigning to the wrapper or the component.  Most examples modify the wrapper, but the page for `MockRender` calls it "mostly useless", begging the question why you'd set inputs through it then.

**Comment by satanTime** [comment]
Hi @jneuhaus20,

thank you for the report.

I'll try to provide more info in documentation about this behavior.

The main problem here is `fixture` and `fixture.point`. From past experience, devs time to time mix them up and treat `fixture` as `fixture.point`. That's why a set of proxies has been added which links `params`, `fixture` (if `params` has that key) and `fixture.point` (if `params` don't provide the key), so if dev mixed up `fixture` and `fixture.point`, he / she should get the desired behavior.

if params are present, then their keys are proxied in `fixture`, otherwise everything from `fixture.point` is proxied to `fixture`.

The idea behind is exactly what you do, once params are provided, they are considered as inputs and won't be modified internally in any case, apart from the direct assignation.
So `params` and the same keys in `fixture.componentInstance` are input values (not `@Input`), and the same keys in `fixture.componentInstance` are properly assigned values  to `@Input` by Angular.

Might you leverage a bit your case about the idea behind assigning a value to `fixture.componentInstance.name` instead of `param.name` and to expect `param.name` to stay the same?

**Comment by jneuhaus20** [comment]
That seems like a lot of headache just to have them both accessible.. what is the case against only providing one? (e.g. the wrapper fully encapsulates the real component, or you provide the component and the wrapper is fully invisible)

Regarding my use case,
- I've got a component with a number of tests and I'm trying to keep each `it` small and focused, while also reducing the amount of boilerplate repetition in each
- It has an output I need to spy on
- It has two interrelated inputs and I need to assert on when they change or don't (think of wrapping a `<select>` and providing the value and an array of options, good UX would reset the value if it's no longer a valid one)

So I end up with code like
```ts
describe('when value1 changes', () => {
    const params = {
      value1: 'something',
      value2: 'a',
      valueChange: jasmine.createSpy('valueChange')
    };

    beforeEach(() => {
      params.valueChange.calls.reset();
      fixture = MockRender(MyComponent, params);
    });

    describe('and value2 is now invalid', () => {
      beforeEach(() => {
        // The wrapper seemed like the proper target, to ensure it's mimicking the way a component containing
        // <app-my-component> would drive its inputs
        fixture.componentInstance.value1 = 'wayDifferent';
        fixture.detectChanges();
      });

      it('should reset value2', () => {
        // The real component's public value is what we actually care about, so it definitely should assert on that
        expect(fixture.point.componentInstance.value2).toEqual(value2Default);
      });

      it('should emit a value change for value2', () => {
        expect(params.valueChange).toHaveBeenCalledWith(value2Default);
      });
    });

    describe('and value2 is still valid', () => {
      beforeEach(() => {
        fixture.componentInstance.value1 = 'similar';
        fixture.detectChanges();
      });

      it('should not change value2', () => {
        // Here I'm referencing params.value2 instead of a literal, because there are other tests doing the same check,
        // I may decide I made a poor choice and change it later, and I don't like scrolling around to remember things
        // that belong in variables.
        expect(fixture.point.componentInstance.value2).toEqual(params.value2);
      });

      it('should not emit a value change', () => {
        expect(params.valueChange).not.toHaveBeenCalled();
      });
    });
```

Shallow copies and setting on the real component certainly work, but I lost several hours trying to find why tests were failing, not expecting the inputs to proxy back on me.

I could allow that the underlying problem is in the documentation.  There's a lot of ways to do inputs, and the simple examples tend to be restricted to creation of things and omit the usage, while the advanced examples jump to a whole big file where it's hard to determine what's applicable to you or not.

While the docs are otherwise very good, stronger guidance and examples like how to re-implement [Angular.io's DashboardHeroComponent test](https://angular.io/guide/testing-components-scenarios#component-with-inputs-and-outputs) and some of the other most common component types/scenarios with `ng-mocks` would provide a massive amount of help.  Converting to MockBuilder and MockRender was super easy, but it's been surprisingly challenging to convert the rest of the (simple-ish) test cases to the corresponding "right" way.

**Comment by satanTime** [comment]
It is :) Regarding the encapsulation, it would have done the work if there had not been support for raw templates like:

```ts
MockRender(`
  <my-complexity [user]="user" (change)="changeSpy($event)">
    <ng-template block="title">TITLE</ng-template>
    <ng-template block="body" let-value>BODY:{{value}}</ng-template>
  </my-complexity>
`, params);
```

In this case, the wrapper component and `my-complexity` are fully disconnected and `point` is the way to communicate to public interface of `my-complexity`, although it could be done like `ngMocks.findInstance(MyComplexityComponent)`, but it may be too complicated for devs to use one extra tool to access what they have just rendered.

---

Another case I was thinking about is objects and functions in `params`. Despite the proxy, their values keep pointers and are updated anyway. And, unfortunately, this is what a dev should keep always in mind.

```ts
const params = {
  user: {
    name: 'test',
  },
};
fixture.componentInstance.user.name = 'updated';
```

In your example, `params.valueChange` has the same issue / behavior.
Despite proxy / spread, `jasmine.createSpy('valueChange')` will keep its state after every `it` and that's why you do the reset via `params.valueChange.calls.reset()`, and so should be processed the other keys in `params`.

---

I would suggest to use [`MockRenderFactory`](https://ng-mocks.sudo.eu/api/MockRender#factory) in your case.
It should help to keep `it` tiny.

```ts
describe('when value1 changes', () => {
    ngMocks.faster();
    const factory = MockRenderFactory(MyComponent, ['value1', 'value2', 'valueChange']);
    beforeAll(() => MockBuilder(MyComponent));
    beforeAll(() => factory.configureTestBed());

    describe('and value2 is now invalid', () => {
      beforeEach(() => {
        fixture = factory({
          value1: 'wayDifferent',
          valueChange: jasmine.createSpy('valueChange')
        });
      });

      it('should reset value2', () => {
        // The real component's public value is what we actually care about, so it definitely should assert on that
        expect(fixture.point.componentInstance.value2).toEqual(value2Default);
      });

      it('should emit a value change for value2', () => {
        expect(fixture.componentInstance.valueChange).toHaveBeenCalledWith(value2Default);
      });
    });

    describe('and value2 is still valid', () => {
      beforeEach(() => {
        fixture = factory({
          value1: 'similar',
          value2: 'a',
          valueChange: jasmine.createSpy('valueChange')
        });
      });

      it('should not change value2', () => {
        expect(fixture.point.componentInstance.value2).toEqual('a');
      });

      it('should not emit a value change', () => {
        expect(fixture.componentInstance.valueChange).not.toHaveBeenCalled();
      });
    });
```

`MockRenderFactory` allows to define view variables for `MockRender` which should be bound to `fixture.componentInstance`. After calling the factory, `fixture.componentInstance` can be used as input params access point and `fixture.point` as output of result.

**Comment by satanTime** [comment]
Hi @jneuhaus20,

would it work for you? Let me know if we should discuss it deeper.

**Comment by jneuhaus20** [comment]
Thanks for the nudge!

I'm not sure what `MockRenderFactory` actually gets me here.  The main difference in your example is setting params like this:
```ts
beforeEach(() => {
        fixture = factory({
          value1: 'similar',
          value2: 'a',
          valueChange: jasmine.createSpy('valueChange')
        });
      });
```
but that's not fundamentally different in code structure or behavior from
```ts
beforeEach(() => {
        fixture = MockRender(MyComponent, {
          value1: 'similar',
          value2: 'a',
          valueChange: jasmine.createSpy('valueChange')
        });
      });
```

**Comment by jneuhaus20** [comment]
Circling back to the original difficulty though: is it necessary that e.g. assigning to `fixture.componentInstance.value1` modifies `params.value1`?  Doing a shallow copy (i.e. `{ ...params }`) is sufficient to avoid the issue entirely; would it break anything for `MockRender` to perform that shallow copy for you?

The current way feels like leaky encapsulation, because the effects of proxying are detectable, and introduce a connection beyond how the language works.  Relating back to Angular, the following is exactly what you would expect:
```ts
const params = { value1: 'something' };

myComponent.input = params;
myComponent.input.value1 = 'something else';

// The language's reference mechanics and common Component patterns both make the following the default expectation
expect(params.value1).toBe('something else'); 
```
but it would take a very unexpected Component implementation for this to pass
```ts
myComponent.input = params; 
myComponent.value1 = 'something else';

expect(params.value1).toBe('something else'); 
```

**Comment by satanTime** [comment]
The thing above isn't right. Because what `ng-mocks` does is more like

```ts
myComponent = params; 
myComponent.value1 = 'something else';
```

The issue with `{ ...params }` is in its child props.

For example when we have:

```ts
const params = { value1: {value2: 'something'} };

const myComponent = { ...params };
myComponent.value1.value2 = 'something else'; // changes the source.
```

To do a deep copy is also not something that devs would expect. Or how deep should we copy?
That's why `ng-mocks` simply uses `params` as it is. If someone needs a deep copy - not a problem, they can do so with calling `MockRender`:

```ts
MockRender(AppComponent, {...params});
```

---

I would say try to write tests with consideration that input data can be changed via `params` only, whereas objects in `fixture` should be used to read values for assertions.

Then `fixture.componentInstance.name = 'modifiedOnWrapper';` is not allowed and should be replaced with `params.name = 'modifiedOnWrapper';` what would make its logic more transparent.

I'll definitely update documentation to put an accent on the pointer / proxy behavior.

**Comment by jneuhaus20** [comment]
Point of clarification: I've been calling `{...params}` a shallow copy because it only copies the first level.  There's a technical argument to be made that `myComponent = params` is _actually_ the shallow copy and the spread operator is a 1-level deep copy, so I'm going to use "clone" instead of "copy" from now on, because it better expresses intent.

I don't think depth of cloning is an issue that should drive the design here, for two reasons:

1. Assignment of an object is a shallow clone, and the default way to "copy" things is to just assign them to a new variable, so 90% or more of libraries suffer from `myComponent.value1.value2 = 'something else'; // changes the source`.  It's basically a language feature at this point.
2. A deep clone is understood to be full-depth.  It's a naturally recursive problem, so the only way to _not_ go full-depth is to do it by hand.  So "how deep" isn't a meaningful question in practice; it's either deep or shallow.

There are plenty of good (or at least good enough) reasons to not change anything, but it's still an objectively confusing design.
* The reference/proxy doesn't arise from standard assumptions and application of language rules. It requires specific knowledge of the implementation to know this will happen.  Documenting this certainly helps, but it's non-intuitive _by definition_.
* It's too easy to do the wrong thing.  Good UX makes it hard or impossible to do the wrong thing, but applying what you know in this scenario leads you to exactly that.  `fixture.componentInstance` is what you set inputs on in "vanilla" Angular tests, and what nearly all testing guidelines, articles, etc. are going to tell you to do.
* The other ways you've suggested just don't match existing conventions or patterns.

You've got a perfectly good wrapper component right there, it would make a ton of sense to say something like "change inputs through `fixture.wrapper.value1`", and then it's far from useless.  Simply changing that name and taking a shallow copy to prevent that proxying would be a game-changing improvement on usability here.

And to be clear, this a fairly narrow critique.  This is an incredibly useful library overall, and you did a fantastic job making `MockBuilder` intuitive and easy.  Simple Type inputs, matching signatures, and a plain-language workflow: "Mock this, keep these, provide that (in the syntax I'm used to)."

**Comment by satanTime** [comment]
Thanks for the info, I hope we'll figure out a possible solution soon.

For now, I don't get your point.

The statement `Assignment of an object is a shallow clone` isn't correct. 

In javascript, when we are operating with objects, we know that it's by language's design that objects are passed by reference into functions or when we assign them.
Therefore, if a developer passes an object somewhere, he / she expect changes by reference.
That's why devs should explicitly spread / clone where they don't want to have side effects, for example, like redux / ngrx do.

```ts
const params = {
 val1: 1,
};
const obj1 = params; // now obj1 ==== params
obj1.val1 = 2; // now params.val1 === 2 too
// this is what happens with fixture.componentInstance
```

As an option, I could throw on `fixture.componentInstance.val1 = 123` an error asking to modify the original params object instead. But then it is a breaking change and all its outcomes. For example, devs who already use the spread operator for default input values and then change them via `fixture.componentInstance.val1` for a specific scenario would be in a trouble.

Also using `MockRender` in `beforeAll` or `beforeEach` when there is a plan to change its params in a test is a bit tricky too.
If we know that our params will differ in an `it`, then we should use `MockRender` in the `it`.
I use `MockRender` inside of `it` mostly, because for every `it` I have different inputs / outputs and using a shared fixture doesn't work anymore.

`fixture.componentInstance` is here only for backward compatibility for devs who didn't read about `fixture.point` and try to do things via `fixture.componentInstance`.

And based on your example at the beginning, unfortunately, I see that documentation still sucks and people try to use `MockRender` in the same way as `TestBed.createComponent`, when the original intention was to avoid a shared fixture and to let devs render things in `it` with 1 line of code, so they could also assert expected failures of missing dependencies etc, what cannot be done in `beforeEach`.

**Comment by satanTime** [comment]
[v12.5.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
